name: dual_teacher_new
channels:
  - defaults
dependencies:
  - python=3.8.20
  - pip
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - zlib
  - libffi
  - ncurses
  - readline
  - sqlite
  - tk
  - xz
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - libgcc-ng=11.2.0
  - libstdcxx-ng=11.2.0
  - libgomp=11.2.0
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu113
      - torch==1.10.1+cu113
      - torchvision==0.11.2+cu113
      - torchaudio==0.10.1+cu113
      - addict==2.4.0
      - appdirs==1.4.4
      - asttokens==3.0.0
      - attrs==25.3.0
      - backcall==0.2.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - cityscapesscripts==2.2.4
      - click==8.1.8
      - codecov==2.1.13
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - coverage==7.6.1
      - cycler==0.12.1
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - flake8==7.1.2
      - fonttools==4.57.0
      - humanfriendly==10.0
      - idna==3.10
      - importlib-resources==6.4.5
      - iniconfig==2.1.0
      - interrogate==1.7.0
      - ipython==8.12.3
      - isort==4.3.21
      - jedi==0.19.2
      - kiwisolver==1.4.7
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mmcv-full==1.3.17
      - numpy==1.24.4
      - opencv-python-headless==4.5.1.48
      - packaging==25.0
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - prettytable==3.11.0
      - prompt-toolkit==3.0.51
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py==1.11.0
      - pycodestyle==2.12.1
      - pyflakes==3.2.0
      - pygments==2.19.1
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - requests==2.32.3
      - six==1.17.0
      - stack-data==0.6.3
      - tabulate==0.9.0
      - terminaltables==3.1.10
      - timm==0.4.12
      - tomli==2.2.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing==3.7.4.3
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - xdoctest==1.2.0
      - yapf==0.31.0
      - zipp==3.20.2
