# arguments for dataset
dataset: rescuenet
nclass: 11
crop_size: 750
data_root: ../../../data/jpk322/RescueNet

# arguments for training
epochs: 30
batch_size: 2 # per GPU x 4 GPUs
lr: 0.005
lr_multi: 1.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: deeplabv3plus
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
