dataset: # Required.
  type: rescuenet_semi
  train:
    data_root: /home/ubuntu/s4mc/datasets/Dataset/RescueNet/Train
    data_list: /home/ubuntu/s4mc/datasets/Dataset/RescueNet/rescuenet-labeled.txt
    flip: True
    GaussianBlur: False
    rand_resize: [0.5, 2.0]
    #rand_rotation: [-10.0, 10.0]
    crop:
      type: rand
      size: [750, 750] # crop image with HxW size
    # acm:
    #   number: 3
    #   no_pad: True
    #   no_slim: True
    #   area_thresh: 0.03
  val:
    data_root: /home/ubuntu/s4mc/datasets/Dataset/RescueNet/Validation
    data_list: /home/ubuntu/s4mc/datasets/Dataset/RescueNet/rescuenet-val.txt
    crop:
      type: center
      size: [3000, 4000] # crop image with HxW size
  batch_size: 4
  n_sup: 900 #NUM
  noise_std: 0.1
  workers: 2
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  ignore_label: 255

trainer: # Required.
  epochs: 200
  eval_on: True
  optimizer:
    type: SGD
    kwargs:
      lr: 0.005
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    mode: poly
    kwargs:
      power: 0.9
  unsupervised:
    TTA: False
    drop_percent:  60 
    apply_aug: cutmix
    two_sample: True
    neigborhood_size: 4
    n_neigbors: 1
    indicator: "margin"


  contrastive:
    low_rank: 3
    high_rank: 20
    current_class_threshold: 0.3
    current_class_negative_threshold: 1
    unsupervised_entropy_ignore: 80
    low_entropy_threshold: 20
    num_negatives: 50
    num_queries: 256
    temperature: 0.5

distributed_params:
  
main_mode:
  eval: False
  compare: False
  compared_pretrain: #path to comaprable model 
  
saver:
  snapshot_dir: checkpoints  
  pretrain:  '' #path to pre-trained, if you train a new, keep '' 
  #(for example: 'checkpoints/366_lower_bound/ckpt_best.pth')

criterion:
  type: CELoss
  kwargs:
    use_weight: False
  cons:
    sample: True
    gamma: 2


net: # Required.
  num_classes: 11
  sync_bn: True
  ema_decay: 0.99
  encoder:
    type: s4mc_utils.models.resnet.resnet101
    kwargs:
      multi_grid: True
      zero_init_residual: True
      fpn: True
      replace_stride_with_dilation: [False, True, True]  #layer0...1 is fixed, layer2...4
  decoder:
    type: s4mc_utils.models.decoder.dec_deeplabv3_plus
    kwargs:
      inner_planes: 256
      dilations: [12, 24, 36]
